# 2D XY Footprint of Robot.
#footprint: [[-0.165, 0.23], [0.165, 0.23], [0.165, -0.23], [-0.165, -0.23]]
robot_radius: 0.18 #0.18

inflation_layer:
 inflation_radius: 1.0
 cost_scaling_factor: 2.58

obstacle_layer:
  obstacle_range: 3.0
  raytrace_range: 2.5
  min_obstacle_height: -1.0
  max_obstacle_height: 1.0

  transform_tolerence: 2.0

  # Robot clears cells that it occupies
  footprint_clearing_enabled: true

  observation_sources: marking_cloud #clearing_cloud

  # lidar_1: {sensor_frame: laser_frame_1, data_type: LaserScan, topic: xv11_scan_1, marking: true, clearing: true, 
  #           min_obstacle_height: 0.05, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  # }
  # lidar_2: {sensor_frame: laser_frame_2, data_type: LaserScan, topic: xv11_scan_2, marking: true, clearing: true, 
  #           min_obstacle_height: 0.05, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  # }

  marking_cloud: {sensor_frame: base_footprint, data_type: PointCloud2, topic: cloud_obstacles_marking, marking: true, clearing: true, 
            min_obstacle_height: -1.0, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0, observation_persistence: 6.0
  }

  clearing_cloud: {sensor_frame: base_footprint, data_type: PointCloud2, topic: cloud_obstacles_clearing, marking: true, clearing: true, 
            min_obstacle_height: -1.0, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0, observation_persistence: 6.0
  }

# # 2D XY Footprint of Robot.
# #footprint: [[-0.165, 0.23], [0.165, 0.23], [0.165, -0.23], [-0.165, -0.23]]
# robot_radius: 0.18 #0.205 #0.18

# # static_layer:
# #   map_topic: map

# inflation_layer:
#   # inflation_radius: 0.1
#   inflation_radius: 0.15 #0.1 #2.5
#  #cost_scaling_factor: 2.58
  
# obstacle_layer:
#   transform_tolerence: 0.5

#   # Robot clears cells that it occupies
#   footprint_clearing_enabled: true

#   observation_sources: marking_cloud #lidar_1 lidar_2 #marking_cloud clearing_cloud
  
#   # lidar_1: {sensor_frame: laser_frame_1, data_type: LaserScan, topic: xv11_scan_1, marking: true, clearing: true, 
#   #           min_obstacle_height: 0.05, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
#   # }
#   # lidar_2: {sensor_frame: laser_frame_2, data_type: LaserScan, topic: xv11_scan_2, marking: true, clearing: true, 
#   #           min_obstacle_height: 0.05, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
#   # }

#   # lidar_1: {sensor_frame: base_laser_1, data_type: PointCloud2, topic: cloud_1, marking: true, clearing: true, 
#   #           min_obstacle_height: 0.05, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
#   # }
#   # lidar_2: {sensor_frame: base_laser_2, data_type: PointCloud2, topic: cloud_2, marking: true, clearing: true, 
#   #           min_obstacle_height: 0.05, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
#   # }

#   marking_cloud: {sensor_frame: base_footprint, data_type: PointCloud2, 
#       topic: cloud_obstacles_marking, marking: true, clearing: true, expected_update_rate: 0.2, min_obstacle_height: -1.0, 
#       max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0, observation_persistence: 6.0
#   }
#   # clearing_cloud: {sensor_frame: base_footprint, data_type: PointCloud2, 
#   #     topic: cloud_obstacles_clearing, marking: true, clearing: true,  min_obstacle_height: 0.05,
#   #     max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 1
#   # }

voxel_layer:
  # obstacle_range: 3.0
  # raytrace_range: 2.5

  # Height of voxel map is resolution * # of voxels.
  # Only need 1 meter for the VS-LIDAR Platform
  z_resolution: 0.1
  z_voxels: 20
  origin_z: -1.0

  # Robot clears cells that it occupies
  footprint_clearing_enabled: true #false

  publish_voxel_map: false

  observation_sources: lidar_1_mark lidar_1_clear lidar_2_mark lidar_2_clear

  # lidar_1: {sensor_frame: base_laser_1, data_type: PointCloud2, topic: cloud_1, marking: true, clearing: true, 
  #           min_obstacle_height: 0.05, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  # }
  # lidar_2: {sensor_frame: base_laser_2, data_type: PointCloud2, topic: cloud_2, marking: true, clearing: true, 
  #           min_obstacle_height: 0.05, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  # }

  lidar_1_mark: {sensor_frame: base_laser_1, data_type: PointCloud2, topic: cloud_1, marking: true, clearing: false, 
            min_obstacle_height: 0.1, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  }
  lidar_1_clear: {sensor_frame: base_laser_1, data_type: PointCloud2, topic: cloud_1, marking: false, clearing: true, 
            min_obstacle_height: -1.0, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  }
  lidar_2_mark: {sensor_frame: base_laser_2, data_type: PointCloud2, topic: cloud_2, marking: true, clearing: false, 
            min_obstacle_height: 0.1, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  }
  lidar_2_clear: {sensor_frame: base_laser_2, data_type: PointCloud2, topic: cloud_2, marking: false, clearing: true, 
            min_obstacle_height: -1.0, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  }  

  # lidar_1_mark: {sensor_frame: laser_frame_1, data_type: LaserScan, topic: xv11_scan_1, marking: true, clearing: false, 
  #           min_obstacle_height: 0.1, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  # }
  # lidar_1_clear: {sensor_frame: laser_frame_1, data_type: LaserScan, topic: xv11_scan_1, marking: false, clearing: true, 
  #           min_obstacle_height: -1.0, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  # }
  # lidar_2_mark: {sensor_frame: laser_frame_2, data_type: LaserScan, topic: xv11_scan_2, marking: true, clearing: false, 
  #           min_obstacle_height: 0.1, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  # }
  # lidar_2_clear: {sensor_frame: laser_frame_2, data_type: LaserScan, topic: xv11_scan_2, marking: false, clearing: true, 
  #           min_obstacle_height: -1.0, max_obstacle_height: 1.0, obstacle_range: 2.5, raytrace_range: 3.0
  # } 


  # marking_cloud: {sensor_frame: base_footprint, data_type: PointCloud2, 
  #     topic: cloud_obstacles, marking: true, clearing: false, expected_update_rate: 0.1, min_obstacle_height: 0.05, max_obstacle_height: 1.0
  # }
  # clearing_cloud: {sensor_frame: base_footprint, data_type: PointCloud2, 
  #     topic: cloud_obstacles_accumulated, marking: true, clearing: true, min_obstacle_height: 0.05, max_obstacle_height: 1.0
  # }  
