global_costmap:
  global_frame: odom
  # global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  rolling_window: false
  # static_map: true
  # rolling_window: false
  width: 100.0
  height: 100.0
  origin_x: -50
  origin_y: -50
  resolution: 0.1
  map_type: costmap

  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
# - {name: static_layer, type: "costmap_2d::StaticLayer"}
