local_costmap:
  global_frame: odom
  #global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05 #0.05
  map_type: costmap

  plugins:
  #- {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
